application: owlection
version: 1-3-1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: router.admin

- url: /vote.*
  script: router.vote

- url: /authenticate/.*
  script: router.authenticate

- url: /tasks/.*
  script: router.tasks
  login: admin

- url: /.*
  script: router.main
