application: uelectus
version: houston-alpha
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static

- url: /api/elections.*
  script: controllers.api.elections.app

- url: /admin/.*
  script: controllers.admin.app

- url: /vote.*
  script: controllers.vote.app

- url: /authenticate/.*
  script: controllers.authenticate.app

- url: /register.*
  script: controllers.register.app

- url: /tasks/.*
  script: controllers.tasks.app
  login: admin

- url: /.*
  script: controllers.main.app
